sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-542.pdf --upload --lsstdoc LDM-542.tex --env=travis --ltd-product ldm-542"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "IJzlhTKSNgrD71gop/axmlHiRDUtY/5WBgTtlKlYPRe4oa0FR01anlvMRZy6Nxc0GLxLG8mpyMz1gGVpo9fr/vY0EJ1Eh1eZM1Wajp9Lf24ThziwqUpjc8wZfrmWGXgHVerems3Fnup4aU80zL4l3psMOHo9IMPfdvvRWAQib0Rz6/1Gl2oy6BSpyxfmj+/T5D2MHmkgcVcNGQ5+D1mc8WtSIxcIvTqdeH+GxJ7kHxGGTuEPna1Bx3R8XhgonaLLbCAbzCF7+PXwHajn2/5QjY+3r/YpQR6MSzqSaMobRn9grugiXxMa7QWfZ1FYvBHm1bZpT1pVAbYsO9pibY7VG4XL4ID8yJjt5e7rAMPUTnF7+m/HPxAOu3ZvOrAkvQQJykxV9ZuyX30K7tq8Bgi9ZT23ZA6afQIzJvurmUCeZZZ8DM88m6Ht2+qOZeKmd905RCmyOMCC3TrQBbkSkVX44Hz527gjIUonIb8fxUN0x9xTRlv7cYVy18TJm08tzEda1wsxclOP8eXT9JuwFMYEfa5uSsNaLq5qYqk7MXMcP35zcPgqxgO6eXl6nMMTWO48AGlGlWnQEJA+W4X/GRm8ZsThn1RLyCkBiZ0cJrCpthvaUm4Gb5EptB64hucSXk8hNLM95etJLhx3bU0oP00XuS6XRLM/zhTGH3bNZHzGprU="
    - secure: "h0wg5+1UTz/0MRKNfeNJh967T6QRiqw15NNRgGeyU7UOrmnAnh/7X2mAUHDb77153GHJ7/RQ44kAOIK3Qj9IJ3voJJTLlMBglAp8Z9Qzd+i/UPBBL3C18/kwHTQfLSV2JdT21elnaiKLypncVEJHs599PVjK+5HmPMHxQV4ZgXk3nY3SZ2hIlBe1wgGc7+FwetOzJoJ90/0Q7I/iq0AaGM5vHcy5v7jq4zbCzSRDC9GYDonwauEuQ53U6W0OboWlPmq/z1sg6MZDF2rC0agDW9tGYnedmSf0l28WfZ0zWfFV+t6P1LL3i7v3n+LGCapHc+jN1p3K4tQ2EkWoFb0UQGvL3xcxAfgKN5+6v8JX10/HF3IpexHvJHyuAy1M8XH98EVqwOK9Nv6C1+YYdMz3LJ6DGl8TfIRsFFBeyjZObACnJPs4mgGrYbufG3tXoaO0CECZulfJ2IhThHWlsqAE/GmKFpxEj30fcFMtKmzFyPwGHCcziPJ+UlFkh1J1Vx4xbnEQoZfxe0oYVeW9Et7wK387lp5axsD77AndQPJV7Xe75Ln3vFZ0YeQK1A6jJ0iKUEiQhjFZw53pLKXOfG9bkn4KxSe8deOjD9m2lFy+/O6FjQLJgxAgk200zEeqKvNxfJauRQxhGd9CfNEoTO2GAwirLMPRfpGHf2IX+puGxiQ="
